/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FuelDappAbi } from "./FuelDappAbi";

export { FuelDappAbi__factory } from "./factories/FuelDappAbi__factory";
